name: CI/CD Pipeline
on:
  push:
    branches:
      - main
      - '**'  # qualquer branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
         java-version: '21'
         distribution: 'temurin'

      - name: Run tests
        run: mvn test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t demo-app .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to ECR
        run: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Docker Tag
        run: docker tag demo-app:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY  }}:${{ github.sha }}

      - name: Push to ECR
        run: docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY  }}:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Authenticate in EKS
        run: aws eks update-kubeconfig --region eu-north-1 --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: kubectl apply
        run:  kubectl apply -f k8s/

      - name: Update tag
        run:  kubectl set image deployment/demo-app demo-app=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY  }}:${{ github.sha }}

